// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: avr_calculator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AverageServiceClient is the client API for AverageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AverageServiceClient interface {
	AverageCalc(ctx context.Context, opts ...grpc.CallOption) (AverageService_AverageCalcClient, error)
}

type averageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAverageServiceClient(cc grpc.ClientConnInterface) AverageServiceClient {
	return &averageServiceClient{cc}
}

func (c *averageServiceClient) AverageCalc(ctx context.Context, opts ...grpc.CallOption) (AverageService_AverageCalcClient, error) {
	stream, err := c.cc.NewStream(ctx, &AverageService_ServiceDesc.Streams[0], "/averagecalculator.AverageService/AverageCalc", opts...)
	if err != nil {
		return nil, err
	}
	x := &averageServiceAverageCalcClient{stream}
	return x, nil
}

type AverageService_AverageCalcClient interface {
	Send(*NumberRequest) error
	CloseAndRecv() (*AverageResponse, error)
	grpc.ClientStream
}

type averageServiceAverageCalcClient struct {
	grpc.ClientStream
}

func (x *averageServiceAverageCalcClient) Send(m *NumberRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *averageServiceAverageCalcClient) CloseAndRecv() (*AverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AverageServiceServer is the server API for AverageService service.
// All implementations must embed UnimplementedAverageServiceServer
// for forward compatibility
type AverageServiceServer interface {
	AverageCalc(AverageService_AverageCalcServer) error
	mustEmbedUnimplementedAverageServiceServer()
}

// UnimplementedAverageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAverageServiceServer struct {
}

func (UnimplementedAverageServiceServer) AverageCalc(AverageService_AverageCalcServer) error {
	return status.Errorf(codes.Unimplemented, "method AverageCalc not implemented")
}
func (UnimplementedAverageServiceServer) mustEmbedUnimplementedAverageServiceServer() {}

// UnsafeAverageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AverageServiceServer will
// result in compilation errors.
type UnsafeAverageServiceServer interface {
	mustEmbedUnimplementedAverageServiceServer()
}

func RegisterAverageServiceServer(s grpc.ServiceRegistrar, srv AverageServiceServer) {
	s.RegisterService(&AverageService_ServiceDesc, srv)
}

func _AverageService_AverageCalc_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AverageServiceServer).AverageCalc(&averageServiceAverageCalcServer{stream})
}

type AverageService_AverageCalcServer interface {
	SendAndClose(*AverageResponse) error
	Recv() (*NumberRequest, error)
	grpc.ServerStream
}

type averageServiceAverageCalcServer struct {
	grpc.ServerStream
}

func (x *averageServiceAverageCalcServer) SendAndClose(m *AverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *averageServiceAverageCalcServer) Recv() (*NumberRequest, error) {
	m := new(NumberRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AverageService_ServiceDesc is the grpc.ServiceDesc for AverageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AverageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "averagecalculator.AverageService",
	HandlerType: (*AverageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AverageCalc",
			Handler:       _AverageService_AverageCalc_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "avr_calculator.proto",
}
